Member back
seosangwon/NBE2_2_Team2 pull request #5
Opened 2024-09-25 06:58 UTC by asklas

2024-09-25 07:20 UTC, seosangwon requested changes

2024-09-25 07:20 UTC, seosangwon commented on src/main/java/com/example/devcoursed/domain/member/member/dto/MemberDTO.java
> +public class MemberDTO {
이름이 그냥 MemberDTO라서 request인지 response인지 무슨 역할을 하는 DTO인지 잘 모르겠어요. 추가로 기능에 맞는 여러개의 dto가 추가 될텐데 한 곳에 관리 하기 위해 inner class로 관리하면 좋을거 같아요! (dto를 관리하는 다른 방법이 있으시다면 반영 안하셔도 됩니다!)

2024-09-25 07:20 UTC, seosangwon commented on src/main/java/com/example/devcoursed/domain/member/member/dto/MemberDTO.java
> +    private Long id;
회원가입 requestDto라면 id는 필요 없을거 같아요

2024-09-25 07:20 UTC, seosangwon commented on src/main/java/com/example/devcoursed/domain/member/member/dto/MemberDTO.java
> +    private LocalDateTime modifiedAt;
createdAt , modifiedAt은 영속성 컨텍스트가 자동 관리를 해줘서 필드 삭제해도 됩니다

2024-09-25 07:20 UTC, seosangwon commented on src/main/java/com/example/devcoursed/domain/member/member/dto/MemberDTO.java
> +    List<Orders> ordersList = new ArrayList<>();
이 필드는 없어도 될 것 같아요

2024-09-25 07:20 UTC, seosangwon commented on src/main/java/com/example/devcoursed/domain/member/member/dto/MemberDTO.java
> +                .ordersList(ordersList)
위 설명과 마찬가지로 없어도 될 것 같아요!

2024-09-25 07:35 UTC, seosangwon commented on src/test/java/com/example/devcoursed/repository/MemberRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
실제 prod에서 사용되는 db를 테스트에 사용하고 싶을 때 사용하는 애노테이션으로 알고 있습니다!

2024-09-25 07:35 UTC, seosangwon commented on src/test/java/com/example/devcoursed/repository/MemberRepositoryTest.java
> +@Transactional(propagation = Propagation.REQUIRED)
사용 의도가 궁금합니다!

2024-09-26 00:42 UTC, asklas commented on src/test/java/com/example/devcoursed/repository/MemberRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
쓰던거 복사해서 가져온거라 몰랐습니다! 주석처리해도 문제없이 동작하네요

2024-09-26 00:43 UTC, asklas commented on src/test/java/com/example/devcoursed/repository/MemberRepositoryTest.java
> +@Transactional(propagation = Propagation.REQUIRED)
위와 동일합니다! 지워도 문제없이 동작하네요

2024-09-26 01:33 UTC, closed without merging